{
 "title": "NATS Adapter Performance",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Message Latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    { "expr": "nats_latency_seconds", "legendFormat": "Latency P{{quantile}}" }
   ]
  },
  {
   "title": "Message Throughput",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Messages/sec" }
   ],
   "targets": [
    { "expr": "rate(nats_messages_total[1m])", "legendFormat": "Messages Rate" }
   ]
  },
  {
   "title": "Client Reconnections",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short", "label": "Count" }
   ],
   "targets": [
    { "expr": "nats_reconnects_total", "legendFormat": "Reconnections" }
   ]
  },
  {
   "title": "Message Backlog",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short", "label": "Messages" }
   ],
   "targets": [
    { "expr": "nats_backlog_depth", "legendFormat": "Backlog Depth" }
   ]
  }
 ]
}