"""
Protobuf Message Definition Module

Provides message type definitions used in the Oppie.xyz system:
- TaskCard: Task card generated by Planner and executed by Executor
- ResultCard: Result card after successful execution
- ErrorCard: Error card after failed execution
- Event: System events (such as GUI interactions, semantic clarification requests, etc.)
""" 