# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x63ommon.proto\x12\noppie.comm\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x19google/protobuf/any.proto\"5\n\x04Step\x12\x13\n\x0binstruction\x18\x01 \x02(\t\x12\x18\n\x10\x65xpected_outcome\x18\x02 \x01(\t\"]\n\x08\x41rtifact\x12\n\n\x02id\x18\x01 \x02(\t\x12\x0c\n\x04type\x18\x02 \x02(\t\x12\x10\n\x08location\x18\x03 \x02(\t\x12\x0f\n\x07\x63ontent\x18\x04 \x01(\x0c\x12\x14\n\x0c\x63ontent_type\x18\x05 \x01(\t\"\xcd\x01\n\x08LogEntry\x12\r\n\x05level\x18\x01 \x02(\t\x12\x0f\n\x07message\x18\x02 \x02(\t\x12-\n\ttimestamp\x18\x03 \x02(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x0e\n\x06source\x18\x04 \x01(\t\x12\x32\n\x07\x63ontext\x18\x05 \x03(\x0b\x32!.oppie.comm.LogEntry.ContextEntry\x1a.\n\x0c\x43ontextEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\xaa\x01\n\x0cTraceContext\x12\x10\n\x08trace_id\x18\x01 \x02(\t\x12\x0f\n\x07span_id\x18\x02 \x02(\t\x12\x0f\n\x07sampled\x18\x03 \x01(\x08\x12\x36\n\x07\x62\x61ggage\x18\x04 \x03(\x0b\x32%.oppie.comm.TraceContext.BaggageEntry\x1a.\n\x0c\x42\x61ggageEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'common_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_LOGENTRY_CONTEXTENTRY']._options = None
  _globals['_LOGENTRY_CONTEXTENTRY']._serialized_options = b'8\001'
  _globals['_TRACECONTEXT_BAGGAGEENTRY']._options = None
  _globals['_TRACECONTEXT_BAGGAGEENTRY']._serialized_options = b'8\001'
  _globals['_STEP']._serialized_start=88
  _globals['_STEP']._serialized_end=141
  _globals['_ARTIFACT']._serialized_start=143
  _globals['_ARTIFACT']._serialized_end=236
  _globals['_LOGENTRY']._serialized_start=239
  _globals['_LOGENTRY']._serialized_end=444
  _globals['_LOGENTRY_CONTEXTENTRY']._serialized_start=398
  _globals['_LOGENTRY_CONTEXTENTRY']._serialized_end=444
  _globals['_TRACECONTEXT']._serialized_start=447
  _globals['_TRACECONTEXT']._serialized_end=617
  _globals['_TRACECONTEXT_BAGGAGEENTRY']._serialized_start=571
  _globals['_TRACECONTEXT_BAGGAGEENTRY']._serialized_end=617
# @@protoc_insertion_point(module_scope)
