# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: error_card.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import common_pb2 as common__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x65rror_card.proto\x12\noppie.comm\x1a\x0c\x63ommon.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x90\x03\n\tErrorCard\x12\x0f\n\x07task_id\x18\x01 \x02(\t\x12\x15\n\rerror_message\x18\x02 \x02(\t\x12\x13\n\x0bstack_trace\x18\x03 \x01(\t\x12\x35\n\x08\x63\x61tegory\x18\x04 \x02(\x0e\x32#.oppie.comm.ErrorCard.ErrorCategory\x12-\n\x0f\x64iagnostic_logs\x18\x05 \x03(\x0b\x32\x14.oppie.comm.LogEntry\x12.\n\nerror_time\x18\x06 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12/\n\rtrace_context\x18\x07 \x01(\x0b\x32\x18.oppie.comm.TraceContext\"\x7f\n\rErrorCategory\x12\x15\n\x11SANDBOX_VIOLATION\x10\x00\x12\x0b\n\x07TIMEOUT\x10\x01\x12\x13\n\x0f\x45XECUTION_ERROR\x10\x02\x12\x16\n\x12\x43\x41PABILITY_MISSING\x10\x03\x12\x12\n\x0eINTERNAL_ERROR\x10\x04\x12\t\n\x05OTHER\x10\x05')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'error_card_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_ERRORCARD']._serialized_start=80
  _globals['_ERRORCARD']._serialized_end=480
  _globals['_ERRORCARD_ERRORCATEGORY']._serialized_start=353
  _globals['_ERRORCARD_ERRORCATEGORY']._serialized_end=480
# @@protoc_insertion_point(module_scope)
