# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc_service.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from . import common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11rpc_service.proto\x12\noppie.comm\x1a\x19google/protobuf/any.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x0c\x63ommon.proto\"i\n\nRpcRequest\x12\x0e\n\x06method\x18\x01 \x02(\t\x12\x0e\n\x06params\x18\x02 \x01(\x0c\x12\n\n\x02id\x18\x03 \x02(\t\x12/\n\rtrace_context\x18\x04 \x01(\x0b\x32\x18.oppie.comm.TraceContext\"\x80\x01\n\x0bRpcResponse\x12\n\n\x02id\x18\x01 \x02(\t\x12\x0e\n\x06result\x18\x02 \x01(\x0c\x12$\n\x05\x65rror\x18\x03 \x01(\x0b\x32\x15.oppie.comm.ErrorInfo\x12/\n\rtrace_context\x18\x04 \x01(\x0b\x32\x18.oppie.comm.TraceContext\"8\n\tErrorInfo\x12\x0c\n\x04\x63ode\x18\x01 \x02(\x05\x12\x0f\n\x07message\x18\x02 \x02(\t\x12\x0c\n\x04\x64\x61ta\x18\x03 \x01(\x0c\"[\n\x13SubscriptionRequest\x12\x13\n\x0b\x65vent_types\x18\x01 \x03(\t\x12/\n\rtrace_context\x18\x02 \x01(\x0b\x32\x18.oppie.comm.TraceContext\"`\n\x05\x45vent\x12\x0c\n\x04type\x18\x01 \x02(\t\x12\x0c\n\x04\x64\x61ta\x18\x02 \x02(\x0c\x12\n\n\x02id\x18\x03 \x02(\t\x12/\n\rtrace_context\x18\x04 \x01(\x0b\x32\x18.oppie.comm.TraceContext2\x8d\x01\n\x0fOppieRpcService\x12\x37\n\x04\x43\x61ll\x12\x16.oppie.comm.RpcRequest\x1a\x17.oppie.comm.RpcResponse\x12\x41\n\tSubscribe\x12\x1f.oppie.comm.SubscriptionRequest\x1a\x11.oppie.comm.Event0\x01')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'rpc_service_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_RPCREQUEST']._serialized_start=103
  _globals['_RPCREQUEST']._serialized_end=208
  _globals['_RPCRESPONSE']._serialized_start=211
  _globals['_RPCRESPONSE']._serialized_end=339
  _globals['_ERRORINFO']._serialized_start=341
  _globals['_ERRORINFO']._serialized_end=397
  _globals['_SUBSCRIPTIONREQUEST']._serialized_start=399
  _globals['_SUBSCRIPTIONREQUEST']._serialized_end=490
  _globals['_EVENT']._serialized_start=492
  _globals['_EVENT']._serialized_end=588
  _globals['_OPPIERPCSERVICE']._serialized_start=591
  _globals['_OPPIERPCSERVICE']._serialized_end=732
# @@protoc_insertion_point(module_scope)
