# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import rpc_service_pb2 as rpc__service__pb2


class OppieRpcServiceStub(object):
    """RPC service definition for use by gRPC adapter
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Call = channel.unary_unary(
                '/oppie.comm.OppieRpcService/Call',
                request_serializer=rpc__service__pb2.RpcRequest.SerializeToString,
                response_deserializer=rpc__service__pb2.RpcResponse.FromString,
                )
        self.Subscribe = channel.unary_stream(
                '/oppie.comm.OppieRpcService/Subscribe',
                request_serializer=rpc__service__pb2.SubscriptionRequest.SerializeToString,
                response_deserializer=rpc__service__pb2.Event.FromString,
                )


class OppieRpcServiceServicer(object):
    """RPC service definition for use by gRPC adapter
    """

    def Call(self, request, context):
        """Generic RPC method call
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Subscribe(self, request, context):
        """Event stream, server pushes events to client
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_OppieRpcServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Call': grpc.unary_unary_rpc_method_handler(
                    servicer.Call,
                    request_deserializer=rpc__service__pb2.RpcRequest.FromString,
                    response_serializer=rpc__service__pb2.RpcResponse.SerializeToString,
            ),
            'Subscribe': grpc.unary_stream_rpc_method_handler(
                    servicer.Subscribe,
                    request_deserializer=rpc__service__pb2.SubscriptionRequest.FromString,
                    response_serializer=rpc__service__pb2.Event.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'oppie.comm.OppieRpcService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class OppieRpcService(object):
    """RPC service definition for use by gRPC adapter
    """

    @staticmethod
    def Call(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/oppie.comm.OppieRpcService/Call',
            rpc__service__pb2.RpcRequest.SerializeToString,
            rpc__service__pb2.RpcResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Subscribe(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/oppie.comm.OppieRpcService/Subscribe',
            rpc__service__pb2.SubscriptionRequest.SerializeToString,
            rpc__service__pb2.Event.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
