# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: task_card.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import common_pb2 as common__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0ftask_card.proto\x12\noppie.comm\x1a\x0c\x63ommon.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xfc\x03\n\x08TaskCard\x12\x0f\n\x07task_id\x18\x01 \x02(\t\x12\x18\n\x10goal_description\x18\x02 \x02(\t\x12#\n\x05steps\x18\x03 \x03(\x0b\x32\x14.oppie.comm.TaskStep\x12/\n\rtrace_context\x18\x04 \x01(\x0b\x32\x18.oppie.comm.TraceContext\x12;\n\x0c\x63ontext_data\x18\x05 \x03(\x0b\x32%.oppie.comm.TaskCard.ContextDataEntry\x12\x1d\n\x15required_capabilities\x18\x06 \x03(\t\x12\x17\n\x0ftimeout_seconds\x18\x07 \x01(\x05\x12\x16\n\x0esem_confidence\x18\x08 \x01(\x01\x12.\n\ncreated_at\x18\t \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x17\n\x0fplanner_version\x18\n \x01(\t\x12\x34\n\x08metadata\x18\x0b \x03(\x0b\x32\".oppie.comm.TaskCard.MetadataEntry\x1a\x32\n\x10\x43ontextDataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x1a/\n\rMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\xfa\x01\n\x08TaskStep\x12\x13\n\x0binstruction\x18\x01 \x02(\t\x12\x18\n\x10\x65xpected_outcome\x18\x02 \x01(\t\x12\x10\n\x08tool_use\x18\x03 \x03(\t\x12\x32\n\nvalidation\x18\x04 \x03(\x0b\x32\x1e.oppie.comm.ValidationCriteria\x12\x12\n\ndepends_on\x18\x05 \x03(\x05\x12\x34\n\x08metadata\x18\x06 \x03(\x0b\x32\".oppie.comm.TaskStep.MetadataEntry\x1a/\n\rMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"K\n\x12ValidationCriteria\x12\x0c\n\x04type\x18\x01 \x02(\t\x12\x10\n\x08\x63riteria\x18\x02 \x02(\t\x12\x15\n\rerror_message\x18\x03 \x01(\t')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'task_card_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_TASKCARD_CONTEXTDATAENTRY']._options = None
  _globals['_TASKCARD_CONTEXTDATAENTRY']._serialized_options = b'8\001'
  _globals['_TASKCARD_METADATAENTRY']._options = None
  _globals['_TASKCARD_METADATAENTRY']._serialized_options = b'8\001'
  _globals['_TASKSTEP_METADATAENTRY']._options = None
  _globals['_TASKSTEP_METADATAENTRY']._serialized_options = b'8\001'
  _globals['_TASKCARD']._serialized_start=79
  _globals['_TASKCARD']._serialized_end=587
  _globals['_TASKCARD_CONTEXTDATAENTRY']._serialized_start=488
  _globals['_TASKCARD_CONTEXTDATAENTRY']._serialized_end=538
  _globals['_TASKCARD_METADATAENTRY']._serialized_start=540
  _globals['_TASKCARD_METADATAENTRY']._serialized_end=587
  _globals['_TASKSTEP']._serialized_start=590
  _globals['_TASKSTEP']._serialized_end=840
  _globals['_TASKSTEP_METADATAENTRY']._serialized_start=540
  _globals['_TASKSTEP_METADATAENTRY']._serialized_end=587
  _globals['_VALIDATIONCRITERIA']._serialized_start=842
  _globals['_VALIDATIONCRITERIA']._serialized_end=917
# @@protoc_insertion_point(module_scope)
